-- Create Stream on Raw Customer Table

CREATE OR REPLACE STREAM STR_CUSTOMER
ON TABLE RAW.CUSTOMER
APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM STR_PRODUCT
ON TABLE RAW.PRODUCT
APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM STR_ORDER
ON TABLE RAW.ORDERS
APPEND_ONLY = FALSE;
