-- Create Stream on Raw Customer Table
-- Sample DBT models created for portfolio purposes. No client or confidential business information is included.

CREATE OR REPLACE STREAM STR_CUSTOMER
ON TABLE RAW.CUSTOMER
APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM STR_PRODUCT
ON TABLE RAW.PRODUCT
APPEND_ONLY = FALSE;

CREATE OR REPLACE STREAM STR_ORDER
ON TABLE RAW.ORDERS
APPEND_ONLY = FALSE;
